---
- hosts: localhost
  tasks:
    - name: Create or Replace Nginx Deployment
      kubernetes.core.k8s:
        state: replaced
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ deployment_name }}"
            namespace: "{{ namespace }}" # ✅ 네임스페이스 변수 사용
            labels:
              app: "{{ application_label }}"
          spec:
            replicas: "{{ replica_cnt | int }}"
            selector:
              matchLabels:
                app: "{{ application_label }}"
            template:
              metadata:
                labels:
                  app: "{{ application_label }}"
              spec:
                containers:
                  - name: "{{ container_name }}"
                    image: "{{ container_image }}"
                    ports:
                      - containerPort: "{{ container_port | int }}"   # ✅ 정수 변환 추가
      register: my_deployment

    - name: Print deployment information
      ansible.builtin.debug:
        var: my_deployment
