---
- hosts: localhost
  tasks:
    - name: Create or Update Nginx Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ deployment_name }}"
            namespace: "{{ k8s_namespace }}"    # ⚡ 안전한 변수명 사용
            labels:
              app: "{{ application_label }}"
          spec:
            replicas: "{{ replica_cnt | int }}"
            selector:
              matchLabels:
                app: "{{ application_label }}"
            template:
              metadata:
                labels:
                  app: "{{ application_label }}"
              spec:
                containers:
                  - name: "{{ container_name }}"
                    image: "{{ container_image }}"
                    ports:
                      #- containerPort: "{{ container_port | int }}"
                      - containerPort: 80
      register: my_deployment

    - name: Print deployment information
      ansible.builtin.debug:
        var: my_deployment
        
    - name: Debug replica type
      ansible.builtin.debug:
        msg: "replica_cnt={{ replica_cnt }} type={{ replica_cnt | type_debug }}"
